load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "arrays",
    srcs = [
        "arrays.go",
        "tictactoe.go",
    ],
)

go_binary(
    name = "slices",
    srcs = [
        "slices.go",
        "pics.go",
        "tictactoe.go",
    ],
)
