load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "simpleinterest",
    srcs = ["simpleinterest.go"],
    importpath = "finance/simpleinterest",
    visibility = ["//financepackage:__pkg__"],
)
