load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "http_request",
    srcs = [
        "http_request.go",
    ],
)

go_binary(
    name = "structs_with_interfaces",
    srcs = [
        "structs_with_interfaces.go",
    ],
)

go_binary(
    name = "types_interfaces",
    srcs = [
        "main.go",
    ],
)

go_binary(
    name = "nill",
    srcs = [
        "nill.go",
    ],
)
