load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

go_binary(
    name = "http_status_channel",
    srcs = [
        "http_status_channel.go",
    ],
)

go_binary(
    name = "http_status_checker",
    srcs = [
        "http_status_checker.go",
    ],
)
